version: "3.8"

services: 
  postgres:
    image: postgres
    ports: 
      - 54320:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 54330:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: your-email@domain.com
      PGADMIN_DEFAULT_PASSWORD: qwer
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: