version: "3.8"

services: 
  postgres:
    image: postgres:13.2
    ports: 
      - 54320:5432
    environment:
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports: 
      - 54330:80
    environment: 
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin: